export const vehicleProps: TVehicleProps = {
  avgSpeed: 1.0,
  localGoalpointRadius: 15,
  maxSteerAngle: 0.52,
  pathFixRadius: 4,
  pathNum: 5,
  pathPerSquareAngle: 1,
  pathStep: 1.0,
  squareAngleLimit: 36,
  squareMapSizeX: 125,
  squareMapSizeY: 125,
  squareSizeX: 0.4,
  squareSizeY: 0.4,
  vehicleWheelBase: 1.9,
  vehicleWheelWidth: 0.05,
  wheelTurnRate: 1.0,
};
